# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage › http://www.lingoes.net/en/translator/langcode.htm
# If it has the same name as one of the files in folder `_data/locales`, the layout language will also be changed,
# otherwise, the layout language will use the default value of 'en'.
lang: en

# Change to your timezone › https://kevinnovak.github.io/Time-Zone-Picker
timezone:

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: Salafiyyah # the main title

tagline: Learn about Islam from the source directly # it will display as the subtitle

description: >- # used by seo meta and the atom feed
  This is a beginner's resource combibing multiple great explanations and free sources of knowledge from trusted entities. This is intended for any Muslim or those interested in Islam. It was initially combined for myself and now for you.
